# SPDX-FileCopyrightText: 2022 Alec Delaney
#
# SPDX-License-Identifier: Unlicense

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3"

python:
  install:
    - requirements: requirements-dev.txt
    - requirements: requirements-doc.txt
